### ISSUE TITLE
`ReferenceError: regeneratorRuntime is not defined`

### ISSUE THREAD

**Issue by garyking** [longseespace/movielens#3]
When I try to use this package, it gives the following error:

```bash
.../node_modules/movielens/dist/index.js:10
  var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(userName, password) {
                               ^

ReferenceError: regeneratorRuntime is not defined
    at .../node_modules/movielens/dist/index.js:10:32
    at Object.<anonymous> (.../node_modules/movielens/dist/index.js:35:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../src/movielens-test.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
```

**Comment by longseespace** [comment]
~~Thanks for reporting the issue. Please provide these additional info, thanks:~~

~~- OS Name/Version~~
~~- Node version~~
